package kr.ac.kopo.week3.day12;

import java.util.Random;

public class ExceptionMain02 {
	public static void main(String[] args) {
		System.out.println("main start....");

		Random r = new Random();
		int num = r.nextInt(3); // 0~2
		System.out.println("num : " + num);
		try {
			System.out.println(10 / num);
		} catch(ArithmeticException ae){
			ae.getStackTrace();
			//System.out.println("이유 : " + ae.getMessage()); // 예외에 대한 이유
		} finally {System.out.println("main end....");}
		
	}
}
